let cakeListItemsData = [{
    id:"abcd",
    name:"Cake-1",
    price: 24.00,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.  Eveniet, consequuntur.",
    img:"assets/images/cake-1.jpg",
    img2:"/products/cake-1.html"
  },{
    id:"efgh",  
    name:"Cake-2",
    price: 10.00,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.  Eveniet, consequuntur.",
    img:"assets/images/cake-2.jpg",
    img2:"/products/cake-2.html",     
  },{ 
    id:"ijkl",
    name:"Cake-3",
    price: 24,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.  Eveniet, consequuntur.",
    img:"assets/images/cake-3.jpg",
    img2:"/products/cake-3.html",
  },{
    id:"mnop",
    name:"Cake-4",
    price: 16.00,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.  Eveniet, consequuntur.",
    img:"assets/images/cake-4.jpg",
    img2:"/products/cake-4.html",
  },{
   id:"qrst",
  name:"Cake-5",
  price: 15.00,
  desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.  Eveniet, consequuntur.",
  img:"assets/images/cake-5.jpg",
  img2:"/products/cake-5.html",
},{
  id:"uvwx",  
  name:"Cake-6",
  price: 10.00,
  desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.  Eveniet, consequuntur.",
  img:"assets/images/cake-6.jpg",
  img2:"/products/cake-6.html",
},{
  id:"yzab",
  name:"Cake-7",
  price: 24,
  desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.  Eveniet, consequuntur.",
  img:"assets/images/cake-7.jpg",
  img2:"/products/cake-7.html",
},{
  id:"cdef",
  name:"Cake-8",
  price: 16.00,
  desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.  Eveniet, consequuntur.",
  img:"assets/images/cake-8.jpg",
  img2:"/products/cake-8.html",
},{
  id:"ghij",
  name:"Cake-9",
  price: 24.00,
  desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.  Eveniet, consequuntur.",
  img:"assets/images/cake-9.jpg",
  img2:"/products/cake-9.html",
},{
  id:"klmn",  
  name:"Cake-10",
  price: 10.00,
  desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.  Eveniet, consequuntur.",
  img:"assets/images/cake-10.jpg",
  img2:"/products/cake-10.html",
},{
  id:"opqr",
  name:"Cake-11",
  price: 24,
  desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.  Eveniet, consequuntur.",
  img:"assets/images/cake-11.jpg",
  img2:"/products/cake-11.html",
},{
  id:"stuv",
  name:"Cake-12",
  price: 16.00,
  desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.  Eveniet, consequuntur.",
  img:"assets/images/cake-12.jpg",
  img2:"/products/cake-12.html",
},{
  id:"wxyz",
  name:"Cake-13",
  price: 24.00,
  desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.  Eveniet, consequuntur.",
  img:"assets/images/cake-13.jpg",
  img2:"/products/cake-13.html"
},{
  id:"rtfg",  
  name:"Cake-14",
  price: 10.00,
  desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.  Eveniet, consequuntur.",
  img:"assets/images/cake-14.jpg",
  img2:"/products/cake-14.html",
},{
  id:"jhyo",
  name:"Cake-15",
  price: 24,
  desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.  Eveniet, consequuntur.",
  img:"assets/images/cake-15.jpg",
  img2:"/products/cake-15.html",
},{
  id:"tyhk",
  name:"Cake-16",
  price: 16.00,
  desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.  Eveniet, consequuntur.",
  img:"assets/images/cake-16.jpg",
  img2:"/products/cake-16.html",
},];